### PR TITLE
More updates to the topology optimization code

### PR DESCRIPTION
**Pull request by bangerth**
@juleoc02: I've gone through the `run()` function and made some more updates. I think I also simplified the code a bit in places. I've got a couple of the helper functions left to read through and document. But go through what I have here already and see what I did in each commit.

I left you two big TODOs. The first one is really a confusion between the `current_state` and `nonlinear_solution` variables. I *think* that you meant to treat these as one and the same, but that's not actually true. The second one may be a bug, but I don't actually know. You should check.

### CODE REVIEW

**Comment by bangerth** [comment]
Another point, on top of the two TODOs that confused me slightly: You in essence have two penalty parameters, the log-barrier factor and the one that appears in the merit function. Both are adjusted over time and are conceptually quite similar. Yet, the log-barrier factor is a local variable in the `run()` function and passed as argument to all sorts of functions, whereas the `penalty_multiplier` is a member variable of the class to which all member functions have access.

I think that the two should be treated the same. I believe that there are no places where you call functions with a "tentative barrier  size", only ever with the one that's currently active. That would suggest that you can make `barrier_size` a member variable as well, and then all of those member functions that currently take it as an argument can drop that argument and use the member variable instead.

**Comment by bangerth** [comment]
Finally, I don't know what changed since the last time I ran the program, but it doesn't produce very interesting output right now. Do you happen to know? It might be worthwhile reverting whatever parameter changed back so that the output is more interesting.

**Comment by juleoc02** [comment]
> It might be worthwhile reverting whatever parameter changed back so that the output is more interesting.

I'm a little worried that the interesting result was the weird (wrong) one we were getting when the filter radius was .25 instead of .251.

**Comment by bangerth** [comment]
I will let you figure this out :-)

**Comment by juleoc02** [comment]
> @juleoc02: I've gone through the `run()` function and made some more updates. I think I also simplified the code a bit in places. I've got a couple of the helper functions left to read through and document. But go through what I have here already and see what I did in each commit.
> 
> I left you two big TODOs. The first one is really a confusion between the `current_state` and `nonlinear_solution` variables. I _think_ that you meant to treat these as one and the same, but that's not actually true. The second one may be a bug, but I don't actually know. You should check.

Yeah. These are meant to be the same. I think that's an artifact from my current code where my class that makes and solves the linear system takes in the "nonlinear solution" as input, but inside the class calls it "current state". Should be easy enough to fix

**Comment by bangerth** [comment]
On 4/1/21 8:39 AM, juleoc02 wrote:
> Yeah. These are meant to be the same. I think that's an artifact from my 
> current code where my class that makes and solves the linear system takes in 
> the "nonlinear solution" as input, but inside the class calls it "current 
> state". Should be easy enough to fix

Get rid of one. If you have "tentative" states, then it might be useful to 
keep it as local variable. Otherwise, use the member variable.

**Pull request merged**
