### PR TITLE
Work through some of the remaining stuff

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Review by juleoc02 — COMMENTED** [review]
I see the ToDos, and I think they make sense, and shouldn't be too crazy to do. I am curious about when to use // vs /*   */ for comments - I know I've basically only used // to mark comments.

I also know I have curly brackets on all of my if's and for's, even if it's only one line because then they're all the same. But, it does look cleaner without them...

**Review by juleoc02 — COMMENTED** [review]
Having the variables in a namespace makes so much sense looking at this.

I (briefly) looked into copying over the sparsity pattern and not redoing the sparsity pattern and I remember having some issue or other with it, but I don't remember what the issue was... I'll look again.

Further down, I need the error of the filtered density compared to applying the filter to the unfiltered density, which is what the weird "filtered unfiltered density" and the adjoint of the same are for.

The next todo asking about filling in the filter matrix uses the (already normalized) filter we made earlier, where each row has a sum of 1, and then just integrates it using the cell->measure() (because the related functions are constant I should just have to multiply by the volume)

**Comment by bangerth** [comment]
On 3/22/21 8:31 PM, juleoc02 wrote:
> I see the ToDos, and I think they make sense, and shouldn't be too crazy to 
> do. I am curious about when to use // vs /* */ for comments - I know I've 
> basically only used // to mark comments.

These changes are due to the way we render the two, not how C++ interprets 
them. The // comments result in text that is then rendered like documentation, 
whereas the /*...*/ is shown as part of the code. Visually, if you want a 
larger piece of code to stay together so that it's easier to grasp it in its 
entirety, it's sometimes easier to use /*...*/ if you just want to mark what 
the next few lines correspond to, rather than making that a complete sentence 
or paragraph.


> I also know I have curly brackets on all of my if's and for's, even if it's 
> only one line because then they're all the same. But, it does look cleaner 
> without them...

It's a style choice. In deal.II (and the tutorials), we don't use curly braces 
for single-statement lines. For a code gallery program, we would have left 
that choice up to you, but since we're shooting for a tutorial, we need to 
follow the relevant style.

**Comment by bangerth** [comment]
On 3/22/21 8:44 PM, juleoc02 wrote:
> I (briefly) looked into copying over the sparsity pattern and not redoing the 
> sparsity pattern and I remember having some issue or other with it, but I 
> don't remember what the issue was... I'll look again.

Try this in separation. Do this one change and see what happens. No other 
changes at the same time.


> Further down, I need the error of the filtered density compared to applying 
> the filter to the unfiltered density, which is what the weird "filtered 
> unfiltered density" and the adjoint of the same are for.

I think it would be useful if you described this in formulas somewhere at the 
appropriate places. Are you saying that you have
   rho = H sigma
but that for some intermediate iterates you have
   rho_k != H sigma_k
and that you need to compute
   rho_k - H sigma_k
for some right hand side or other?


> The next todo asking about filling in the filter matrix uses the (already 
> normalized) filter we made earlier, where each row has a sum of 1, and then 
> just integrates it using the cell->measure() (because the related functions 
> are constant I should just have to multiply by the volume)

I'm afraid I don't quite understand :-)

In all of these places, if you find a TODO where you think the code is correct 
and already optimal, please remove the TODO and replace it by a description of 
what is happening there. If I don't understand, chances are that others don't 
either ;-)

**Pull request merged**
